### PR TITLE
[WIP] Rewrite

### PR DESCRIPTION
**Pull request by nonnontrivial**

### CODE REVIEW

**Comment by devillexio** [comment]
There seems to be an issue with the latest version of the export script on this branch (`extend-api-support`).

We get the following error when attempting to exporting a specific project we have in Botmock that has Call To Action (CTA) buttons:
```
Error: button is unsupported
    at Provider.create (/Users/devillex/Developer/temp/botmock-dialogflow-export/lib/providers/index.js:22:13)
    at JSON.stringify.responses.messages.map.message (/Users/devillex/Developer/temp/botmock-dialogflow-export/index.js:148:30)
    at Array.map (<anonymous>)
    at _f16‍.r.Promise.all.board.messages.filter.map (/Users/devillex/Developer/temp/botmock-dialogflow-export/index.js:147:61)
```

When we changed the CTA buttons to Quick Replies, we got this error instead:
```
Error: twitter_quick_replies is unsupported
    at Provider.create (/Users/devillex/Developer/temp/botmock-dialogflow-export/lib/providers/index.js:22:13)
    at JSON.stringify.responses.messages.map.message (/Users/devillex/Developer/temp/botmock-dialogflow-export/index.js:148:30)
    at Array.map (<anonymous>)
    at _f16‍.r.Promise.all.board.messages.filter.map (/Users/devillex/Developer/temp/botmock-dialogflow-export/index.js:147:61)
```

Here is the script config for the project:
```
BOTMOCK_TEAM_ID="6072"
BOTMOCK_PROJECT_ID="5d5f2ca0-304a-11e9-b7bf-6d1c9042b1ec"
BOTMOCK_BOARD_ID="5d5ffde0-304a-11e9-b86b-070e321cdeb8"
```

Let me know if we can add a user to the project in Botmock to see the details. Note that this is a Twitter bot.

**Comment by obaid** [comment]
Thanks, @devillexio -- we are looking into this issue and will update you once we have addressed it in this PR. :)

**Comment by nonnontrivial** [comment]
Hey @devillexio , can you try again on the latest commit?

**Comment by devillexio** [comment]
Thanks for your help and ongoing support. With the updated script we managed to run the export tool for the aforementioned project. We did however run into an issue with exporting a project for a FB bot.

This is the error that we got:
```
npm start

> botmock-dialogflow-export@1.0.0 start /Users/deville.weppenaar/Developer/addynamo/bluerobot/botmock-dialogflow-export
> node -r esm index.js

(node:46488) ExperimentalWarning: The fs.promises API is experimental
TypeError: (intermediate value) is not iterable
    at _903‍.r (/Users/deville.weppenaar/Developer/addynamo/bluerobot/botmock-dialogflow-export/index.js:230:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Config for the project:
```
BOTMOCK_TEAM_ID="6072"
BOTMOCK_PROJECT_ID="6a2fd840-38f5-11e9-87e1-0364c6690265"
BOTMOCK_BOARD_ID="6a30ac40-38f5-11e9-be7e-330f68e920a8"
```

**Comment by devillexio** [comment]
Unfortunately I still get an error on the latest branch, albeit a different one:
```
npm start

> botmock-dialogflow-export@1.0.0 start /Users/devillex/Developer/temp/botmock-dialogflow-export
> node -r esm index.js

(node:19988) ExperimentalWarning: The fs.promises API is experimental
TypeError: entities is not iterable
    at _f36‍.r (/Users/devillex/Developer/temp/botmock-dialogflow-export/index.js:231:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I run the script again without first deleting the `output` folder, I also get the following error:
```
npm start

> botmock-dialogflow-export@1.0.0 start /Users/devillex/Developer/temp/botmock-dialogflow-export
> node -r esm index.js

TypeError: Cannot read property 'messages' of undefined
    at _f36‍.r (/Users/devillex/Developer/temp/botmock-dialogflow-export/index.js:31:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm not sure, but this may be due to the environmental state left after the first error.

This is using the same config as previous:
```
BOTMOCK_TEAM_ID="6072"
BOTMOCK_PROJECT_ID="6a2fd840-38f5-11e9-87e1-0364c6690265"
BOTMOCK_BOARD_ID="6a30ac40-38f5-11e9-be7e-330f68e920a8"
```

**Comment by obaid** [comment]
Thanks, @devillexio. Is it possible for you to invite me (obaid@botmock.com) and Kevin (kevin@botmock.com) to the project? Just so we can debug the issue better.

**Comment by devillexio** [comment]
No problem @obaid. Absolutely. I'll ask Kyle to add you to the project as soon as possible. Will ping you when it has been shared.

**Pull request merged**
